name: Codecov Action
description: Test results and coverage reporting for GitHub Actions with multi-format support

inputs:
  # Authentication
  token:
    description: GitHub token for API access and artifacts
    required: true

  # Coverage file discovery (Codecov-style)
  files:
    description: Comma-separated explicit list of coverage files to process
    required: false
  directory:
    description: Folder to search for coverage files. Defaults to current working directory
    required: false
    default: '.'
  exclude:
    description: Comma-separated list of folders/patterns to exclude from search
    required: false

  # Format handling
  coverage-format:
    description: 'Coverage format hint (auto, clover, cobertura, jacoco, lcov, istanbul, go). Auto-detects if not specified'
    required: false
    default: 'auto'
  disable-search:
    description: Disable automatic search for coverage files. Use with "files" input
    required: false
    default: 'false'

  # Behavior flags (Codecov-style)
  fail-ci-if-error:
    description: Exit with non-zero code if coverage processing fails
    required: false
    default: 'false'
  handle-no-reports-found:
    description: Do not fail if no coverage reports are found
    required: false
    default: 'false'
  verbose:
    description: Enable verbose logging for debugging
    required: false
    default: 'false'

  # Grouping and identification (Codecov-style)
  flags:
    description: Comma-separated list of flags to tag this coverage upload (e.g., unittests, frontend)
    required: false
  name:
    description: Custom name for this coverage upload. Visible in reports
    required: false

  # Comparison settings
  base-branch:
    description: Base branch to compare results against
    required: false
    default: 'main'

  # Test results
  junit-xml-pattern:
    description: Glob pattern for finding JUnit XML files
    required: false
    default: './**/*.junit.xml'
  enable-tests:
    description: Enable test results reporting
    required: false
    default: 'true'
  enable-coverage:
    description: Enable coverage reporting
    required: false
    default: 'true'
  post-pr-comment:
    description: Post results as a PR comment (in addition to Job Summary)
    required: false
    default: 'false'

  # Legacy input (deprecated, use 'files' or 'directory' instead)
  coverage-xml-pattern:
    description: '[Deprecated] Glob pattern for finding coverage XML files. Use files/directory instead.'
    required: false

outputs:
  # Test outputs
  total-tests:
    description: Total number of tests run
  passed-tests:
    description: Number of passed tests
  failed-tests:
    description: Number of failed tests
  test-pass-rate:
    description: Percentage of tests that passed
  tests-added:
    description: Number of tests added compared to base branch
  tests-removed:
    description: Number of tests removed compared to base branch
  tests-fixed:
    description: Number of tests that changed from failing to passing
  tests-broken:
    description: Number of tests that changed from passing to failing
  
  # Coverage outputs
  line-coverage:
    description: Line coverage percentage
  branch-coverage:
    description: Branch coverage percentage
  coverage-change:
    description: Change in line coverage compared to base branch
  branch-coverage-change:
    description: Change in branch coverage compared to base branch
  coverage-improved:
    description: Whether coverage improved compared to base branch (true/false)
  coverage-format:
    description: The detected or specified coverage format used
  coverage-name:
    description: The custom name provided for the coverage upload
  coverage-flags:
    description: The flags provided for the coverage upload

runs:
  using: node20
  main: dist/index.js
