import type { AggregatedTestResults, TestComparison } from "../types/test-results.js";

export class PRCommentFormatter {
  /**
   * Format test results as a markdown comment for PRs
   */
  formatComment(results: AggregatedTestResults): string {
    const lines: string[] = [];

    // Header
    lines.push("## Test Results 🧪");
    lines.push("");

    // Summary line with emoji indicators
    const passEmoji = results.passedTests > 0 ? "✅" : "";
    const failEmoji = results.failedTests > 0 ? "❌" : "";
    const skipEmoji = results.skippedTests > 0 ? "⏭️" : "";

    const summaryParts: string[] = [];

    if (passEmoji) {
      summaryParts.push(`${passEmoji} **${results.passedTests} passed**`);
    }
    if (failEmoji) {
      summaryParts.push(`${failEmoji} **${results.failedTests} failed**`);
    }
    if (skipEmoji) {
      summaryParts.push(`${skipEmoji} **${results.skippedTests} skipped**`);
    }

    // Add total and pass rate
    summaryParts.push(`**Total: ${results.totalTests}**`);
    summaryParts.push(`**Pass Rate: ${results.passRate}%**`);

    lines.push(summaryParts.join(" | "));
    lines.push("");

    // Execution time
    lines.push(`⏱️ **Execution Time:** ${this.formatTime(results.totalTime)}`);
    lines.push("");

    // Add comparison section if available
    if (results.comparison) {
      this.addComparisonSection(lines, results.comparison);
    }

    // Show failed tests if any
    if (results.failedTests > 0 && results.failedTestCases.length > 0) {
      lines.push("### ❌ Failed Tests");
      lines.push("");

      for (const { suiteName, testCase } of results.failedTestCases) {
        // Test header
        lines.push(`#### \`${testCase.name}\``);
        lines.push(`**File:** \`${testCase.classname}\``);

        if (suiteName && suiteName !== testCase.classname) {
          lines.push(`**Suite:** \`${suiteName}\``);
        }

        if (testCase.failure) {
          lines.push(`**Error:** ${testCase.failure.message}`);
          lines.push("");

          // Stack trace in collapsible details
          if (testCase.failure.content) {
            lines.push("<details>");
            lines.push("<summary>Stack Trace</summary>");
            lines.push("");
            lines.push("```");
            lines.push(testCase.failure.content.trim());
            lines.push("```");
            lines.push("");
            lines.push("</details>");
            lines.push("");
          }
        }
      }
    } else if (results.failedTests === 0) {
      // Success message
      lines.push("### ✅ All Tests Passed!");
      lines.push("");
      lines.push("Great job! All tests are passing successfully.");
      lines.push("");
    }

    // Footer
    lines.push("---");
    lines.push("*Generated by Codecov Action*");

    return lines.join("\n");
  }

  /**
   * Add comparison section to the comment
   */
  private addComparisonSection(lines: string[], comparison: TestComparison): void {
    lines.push("### 📊 Comparison with Base Branch");
    lines.push("");

    // Summary table
    lines.push("| Metric | Change |");
    lines.push("|--------|--------|");
    lines.push(`| Total Tests | ${this.formatDelta(comparison.deltaTotal)} |`);
    lines.push(`| Passed Tests | ${this.formatDelta(comparison.deltaPassed)} |`);
    lines.push(`| Failed Tests | ${this.formatDelta(comparison.deltaFailed)} |`);
    lines.push(`| Skipped Tests | ${this.formatDelta(comparison.deltaSkipped)} |`);
    lines.push("");

    // Tests broken (regressions)
    if (comparison.testsBroken.length > 0) {
      lines.push(`#### 🔴 Tests Broken (${comparison.testsBroken.length})`);
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>View broken tests</summary>");
      lines.push("");
      for (const testChange of comparison.testsBroken) {
        lines.push(`- \`${testChange.identifier.testName}\``);
        lines.push(`  - **File:** \`${testChange.identifier.classname}\``);
        if (testChange.testCase.failure) {
          lines.push(`  - **Error:** ${testChange.testCase.failure.message}`);
        }
      }
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }

    // Tests fixed (improvements)
    if (comparison.testsFixed.length > 0) {
      lines.push(`#### 🟢 Tests Fixed (${comparison.testsFixed.length})`);
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>View fixed tests</summary>");
      lines.push("");
      for (const testChange of comparison.testsFixed) {
        lines.push(`- \`${testChange.identifier.testName}\``);
        lines.push(`  - **File:** \`${testChange.identifier.classname}\``);
      }
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }

    // Tests added
    if (comparison.testsAdded.length > 0) {
      lines.push(`#### ➕ New Tests (${comparison.testsAdded.length})`);
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>View new tests</summary>");
      lines.push("");
      for (const testChange of comparison.testsAdded) {
        lines.push(`- \`${testChange.identifier.testName}\``);
        lines.push(`  - **File:** \`${testChange.identifier.classname}\``);
        if (testChange.testCase.failure) {
          lines.push(`  - **Status:** ❌ Failing`);
        } else {
          lines.push(`  - **Status:** ✅ Passing`);
        }
      }
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }

    // Tests removed
    if (comparison.testsRemoved.length > 0) {
      lines.push(`#### ➖ Removed Tests (${comparison.testsRemoved.length})`);
      lines.push("");
      lines.push("<details>");
      lines.push("<summary>View removed tests</summary>");
      lines.push("");
      for (const testChange of comparison.testsRemoved) {
        lines.push(`- \`${testChange.identifier.testName}\``);
        lines.push(`  - **File:** \`${testChange.identifier.classname}\``);
      }
      lines.push("");
      lines.push("</details>");
      lines.push("");
    }

    // Summary message
    if (
      comparison.testsBroken.length === 0 &&
      comparison.testsFixed.length === 0 &&
      comparison.testsAdded.length === 0 &&
      comparison.testsRemoved.length === 0
    ) {
      lines.push("✨ No test changes detected");
      lines.push("");
    }
  }

  /**
   * Format a delta value with appropriate sign and emoji
   */
  private formatDelta(delta: number): string {
    if (delta === 0) {
      return "—";
    }
    const sign = delta > 0 ? "+" : "";
    const emoji = delta > 0 ? "📈" : "📉";
    return `${emoji} ${sign}${delta}`;
  }

  /**
   * Format execution time in a human-readable way
   */
  private formatTime(seconds: number): string {
    if (seconds < 1) {
      return `${Math.round(seconds * 1000)}ms`;
    }
    if (seconds < 60) {
      return `${seconds.toFixed(2)}s`;
    }
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = seconds % 60;
    return `${minutes}m ${remainingSeconds.toFixed(0)}s`;
  }

  /**
   * Generate a unique identifier for the comment
   * This helps identify comments created by this action
   */
  static getCommentIdentifier(): string {
    return "<!-- codecov-action-test-results -->";
  }

  /**
   * Add identifier to comment body
   */
  addIdentifier(comment: string): string {
    return `${PRCommentFormatter.getCommentIdentifier()}\n${comment}`;
  }
}
